colorscheme slate
set signcolumn=yes
set syntax=on
set cmdheight=2
set shortmess=a
set number
set relativenumber
set hidden
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set smartindent
set nowrap
set scrolloff=8
set incsearch
set colorcolumn=80
set hlsearch
